sonar.exclusions=apps/frontend/*.config.*,apps/frontend/electron/main.js
sonar.tests=tests,apps/backend/tests,services/tests
sonar.test.inclusions=**/tests/**
sonar.coverage.exclusions=tests/**,**/conftest.py
sonar.cpd.exclusions=tests/nfr/**
sonar.sources=apps,services,packages