# basically a makefile for windows 
version: "3"

dotenv: [".env"]

vars:
  FRONTEND_DIR: apps/frontend
  BACKEND_APP: apps/backend/app/main.py
  SERVICES_DIR: services

tasks:

  install:
    desc: Install backend + frontend deps
    cmds:
      - uv sync --all-groups --python 3.11
      - cmd: yarn install
        dir: "{{.FRONTEND_DIR}}"

  dev:
    desc: Runs backend and frontend in dev mode
    deps:
      - backend-dev
      - frontend-dev
    
  backend-dev:
    internal: true # not possible to call outside
    cmds:
      - uv run fastapi dev {{.BACKEND_APP}}  --port {{.BACKENDPORT}}

  frontend-dev:
    internal: true
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - yarn dev
  
  build:
    desc: Builds the backend and frontend
    deps:
      - backend-build
      - frontend-build
  
  backend-build:
    internal: true
    cmds:
      - uv run fastapi run  {{.BACKEND_APP}} --port {{.BACKENDPORT}}
  
  frontend-build:
    internal: true
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - yarn build

  test:
    desc: Runs backend, frontend, and services testing
    cmds:
      - uv run pytest --cov --cov-report=term-missing
      - cmd: yarn test
        dir: "{{FRONTEND_DIR}}"
  
  lint:
    desc: Runs Ruff lint checks
    cmds:
      - uv run ruff check --output-format=github
      - cmd: yarn lint
        dir: "{{FRONTEND_DIR}}"

  fix:
    desc: Automatically fixes Ruff issues
    cmds:
      - uv run ruff format .
      - uv run ruff check --fix .
      - cmd: yarn lint
        dir: "{{FRONTEND_DIR}}"
  
  services-install:
    desc: Install services package
    cmds:
      - pip install -e "{{.SERVICES_DIR}}[dev]" --break-system-packages
  
  services-test:
    desc: Runs test cases in services
    cmds:
      - uv run pytest services/tests

  backend-test:
    desc: Runs backend testing
    cmds:
      - uv run pytest --cov --cov-report=term-missing

  frontend-test:
    desc: Runs frontend testing
    cmds:
    - cmd: yarn test
      dir: "{{FRONTEND_DIR}}"
  