"""
Regenerate the NFR traceability matrix from the evidence JSON files.

Run after the suite:  python tests/nfr/report.py
Writes docs/nfr/MATRIX.md, reading every docs/nfr/evidence/*.json produced by
the tests. The 'actual' column is generated here, never typed by hand.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
EVIDENCE_DIR = REPO_ROOT / 'docs' / 'nfr' / 'evidence'
OUTPUT = REPO_ROOT / 'docs' / 'nfr' / 'MATRIX.md'

# id -> (SRS ref, quantified requirement, tactic, test)
ROWS = {
	# --- NFR1 Performance ---
	'QR-03': ('NFR1.1', 'p95 latency <= 200 ms', 'Pure-geometry classifier', 'test_latency.py'),
	'QR-18': (
		'NFR1.2',
		'Pipeline stays bounded under load',
		'Drop-oldest frame queue',
		'test_realtime_robustness.py',
	),
	# --- NFR2 Security ---
	'QR-07': ('NFR2.1', 'Session token <= 30 min', 'Short-lived JWT', 'test_security.py'),
	'QR-12': (
		'NFR2.1',
		'Invalid tokens rejected',
		'JWT exp/aud/iss/sig checks',
		'test_token_validation.py',
	),
	'QR-08': (
		'NFR2.2',
		'Password hash cost >= 12 rounds',
		'Configurable bcrypt rounds',
		'test_password_security.py',
	),
	'QR-09': (
		'NFR2.2',
		'Weak passwords rejected',
		'Strength policy regexes',
		'test_password_security.py',
	),
	'QR-10': (
		'NFR2.2',
		'Password hashes salted',
		'bcrypt gensalt',
		'test_password_security.py',
	),
	# --- NFR3 Reliability ---
	'QR-01': ('NFR3.1', 'Gesture accuracy >= 95% (ML)', 'ML recognizer (MLP)', 'test_accuracy.py'),
	'QR-02': (
		'NFR3.1',
		'Every gesture >= 95% (ML)',
		'ML recognizer (MLP)',
		'test_accuracy.py',
	),
	'QR-01-rule': (
		'NFR3.1',
		'Rule-based accuracy (informational)',
		'Rule-based ceiling',
		'test_accuracy.py',
	),
	'QR-06': (
		'NFR3.2',
		'Confidence gate >= 0.85',
		'MIN_CONFIDENCE filter',
		'test_command_mapping.py',
	),
	'QR-19': (
		'NFR3.2',
		'Single-frame noise suppressed',
		'GestureStabilizer voting',
		'test_realtime_robustness.py',
	),
	'QR-04': (
		'NFR3.2',
		'All single-hand gestures mapped',
		'SINGLE_HAND_MAP',
		'test_command_mapping.py',
	),
	'QR-05': (
		'NFR3.2',
		'All two-hand combos resolve',
		'Two-hand maps + _resolve',
		'test_command_mapping.py',
	),
	'QR-13': (
		'NFR3.3',
		'E-stop always critical priority',
		'Command priority elevation',
		'test_safety.py',
	),
	'QR-14': (
		'NFR3.3',
		'E-stop grounds the drone',
		'Adapter emergency_stop',
		'test_safety.py',
	),
}


def main() -> None:
	lines = [
		'# NFR Traceability Matrix',
		'',
		'Generated by `tests/nfr/report.py` from `docs/nfr/evidence/`. Do not edit by hand.',
		'',
		'| ID | SRS | Requirement | Tactic | Test | Target | Actual | Result |',
		'|----|-----|-------------|--------|------|--------|--------|--------|',
	]

	measured = passing = 0
	for qr_id, (srs, req, tactic, test) in ROWS.items():
		path = EVIDENCE_DIR / f'{qr_id}.json'
		if path.exists():
			data = json.loads(path.read_text())
			measured += 1
			result = 'PASS' if data.get('pass') else 'FAIL'
			passing += data.get('pass', False)
			actual, target = data.get('actual'), data.get('target')
		else:
			result, actual, target = 'MISSING', 'not measured', '-'
		lines.append(
			f'| {qr_id} | {srs} | {req} | {tactic} | {test} | {target} | {actual} | {result} |'
		)

	lines += ['', f'**{measured}/{len(ROWS)} measured, {passing} passing.**', '']

	OUTPUT.parent.mkdir(parents=True, exist_ok=True)
	OUTPUT.write_text('\n'.join(lines) + '\n')
	print(
		f'wrote {OUTPUT.relative_to(REPO_ROOT)} ({measured}/{len(ROWS)} measured, {passing} pasing)'
	)


if __name__ == '__main__':
	main()
