"""
Regenerate the NFR traceability matrix from the evidence JSON files.

Run after the suite:  python tests/nfr/report.py
Writes docs/nfr/MATRIX.md, reading every docs/nfr/evidence/*.json produced by
the tests. The 'actual' column is generated here, never typed by hand.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
EVIDENCE_DIR = REPO_ROOT / 'docs' / 'nfr' / 'evidence'
OUTPUT = REPO_ROOT / 'docs' / 'nfr' / 'MATRIX.md'

# id -> (SRS ref, quantified requirement, tactic, test)
ROWS = {
	'QR-01': ('NFR3.1', 'Gesture accuracy >= 95%', 'Rule-based recognizer', 'test_accuracy.py'),
	'QR-02': ('NFR3.2', 'Every gesture >= 95%', 'Per-gesture geometry rules', 'test_accuracy.py'),
	'QR-03': ('NFR1.1', 'p95 recognition < 50ms', 'Pure-geometry classifier', 'test_latency.py'),
	'QR-04': (
		'NFR2.4',
		'All single-hand gestures mapped',
		'SINGLE_HAND_MAP',
		'test_command_mapping.py',
	),
	'QR-05': (
		'NFR2.4',
		'All two-hand combos resolve',
		'Two-hand maps + _resolve',
		'test_command_mapping.py',
	),
	'QR-06': (
		'NFR2.4',
		'Confidence gate >= 0.85',
		'MIN_CONFIDENCE filter',
		'test_command_mapping.py',
	),
	'QR-07': ('NFR4.1', 'Token lifetime <= 30 min', 'Short-lived JWT', 'test_security.py'),
}


def main() -> None:
	lines = [
		'# NFR Traceability Matrix',
		'',
		'Generated by `tests/nfr/report.py` from `docs/nfr/evidence/`. Do not edit by hand.',
		'',
		'| ID | SRS | Requirement | Tactic | Test | Target | Actual | Result |',
		'|----|-----|-------------|--------|------|--------|--------|--------|',
	]

	measured = passing = 0
	for qr_id, (srs, req, tactic, test) in ROWS.items():
		path = EVIDENCE_DIR / f'{qr_id}.json'
		if path.exists():
			data = json.loads(path.read_text())
			measured += 1
			result = 'PASS' if data.get('pass') else 'FAIL'
			passing += data.get('pass', False)
			actual, target = data.get('actual'), data.get('target')
		else:
			result, actual, target = 'MISSING', 'not measured', '-'
		lines.append(
			f'| {qr_id} | {srs} | {req} | {tactic} | {test} | {target} | {actual} | {result} |'
		)

	lines += ['', f'**{measured}/{len(ROWS)} measured, {passing} passing.**', '']

	OUTPUT.parent.mkdir(parents=True, exist_ok=True)
	OUTPUT.write_text('\n'.join(lines) + '\n')
	print(
		f'wrote {OUTPUT.relative_to(REPO_ROOT)} ({measured}/{len(ROWS)} measured, {passing} pasing)'
	)


if __name__ == '__main__':
	main()
