name: Lint

on: 
  push:
    branches: ['**']   
  pull_request:
    branches: ['**'] 


jobs:
  lint-backend:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: apps/backend

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with: 
          enable-cache: true
      - uses: actions/setup-python@v5
        with: 
          python-version: 3.11

      - name: Install Dependencies
        run: make install

      - name: Ruff Linter
        run: make lint


  lint-frontend:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: apps/frontend

    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.22.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn lint

      - name: Check Prettier formatting
        run: yarn format:check