name: CI Pipeline

on: 
    push:
        branches:
            - main
            - dev

    pull_request:
        branches: 
            - main
            - dev


jobs:

    lint: 
        name: Lint
        uses: ./.github/workflows/lint.yml

    test-apps: 
        name: Test Apps
        needs: lint
        uses: ./.github/workflows/test.yml
        with:
            directory: app

    test-services:
        name: Test Services
        needs: lint
        uses: ./.github/workflows/test.yml
        with:
            directory: services

    test-integration: 
        name: Test Integration
        needs: [lint, test-services, test-services]
        uses: ./.github/workflows/test.yml
        with:
            directory: services